name: GitHub-Actions Caching Demo

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  custom-cache-demo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Custom cache for pip dependencies
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Cache for downloaded data/models
    - name: Cache downloaded models
      uses: actions/cache@v3
      with:
        path: models/
        key: models-${{ hashFiles('scripts/download-models.py') }}

    - name: Download models
      run: python scripts/download-models.py
