name: Artifacts Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build application
        run: |
          echo "Building the app..."
          mkdir dist
          echo "Hello World v1.0" > dist/app.txt
          echo "Build completed at $(date)" > dist/build-info.txt
      
      # UPLOAD: Save build results
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-app-build
          path: dist/
          
  deploy:
    needs: build  # Wait for build job
    runs-on: ubuntu-latest
    steps:
      # DOWNLOAD: Get the built files
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: my-app-build
          
      - name: Deploy application
        run: |
          echo "Deploying files we built earlier:"
          cat app.txt
          cat build-info.txt
